# This is a basic workflow that is manually triggered

name: release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      version:
        description: "version"
        required: true
        default: "0"

jobs:
  build_release:
    name: create release
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./src
      
    - name: Build
      run: dotnet build ./src/Hangfire.Mongo/Hangfire.Mongo.csproj -c Release --no-restore /p:AssemblyVersion=${{ github.event.inputs.version }} /p:Version=${{ github.event.inputs.version }}

    - name: Test
      run: dotnet test ./src -c Release --no-build --verbosity normal


    - name: Create a Release
      uses: softprops/action-gh-release@v1
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.event.inputs.version }}
          tag_name: ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
        
    - name: Publish to nuget.org
      run: dotnet nuget push src/Hangfire.Mongo/bin/Release/Hangfire.Mongo.${{ github.event.inputs.version }}.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
